services:
  - type: web
    plan: free
    name: FileToLink
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m Adarsh
    repo: https://github.com/itzraiyan2580/FileToLink/      
    branch: Tech_VJ
    envVars:
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: BIN_CHANNEL 
        sync: false
      - key: OWNER_USERNAME 
        sync: false
      - key: OWNER_ID 
        sync: false
      - key: DATABASE_URL 
        sync: false
      - key: UPDATES_CHANNEL
        sync: false
      - key: FQDN
        sync: false
